name: Matrix Test

on: [ workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        a: [ a1, a2, a3 ]
        b: [ b1, b2, b3 ]
    steps:
      - uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/download@erichaagdev/unique-receipt-artifact
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/experiment-3@erichaagdev/unique-receipt-artifact
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        with:
          gitRepo: https://github.com/etiennestuder/java-ordered-properties
          tasks: build
          gradleEnterpriseUrl: https://ge.solutions-team.gradle.com
