on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/on-push-paths.yml
      - ${{ github.workflow }}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.workflow }} triggered!"
